### ISSUE TITLE
Hoisting exercises do not (apparently) teach hoisting?!

### ISSUE THREAD

**Issue by CaptRat** [learn-co-curriculum/js-hoisting-readme#14]
I just spent an hour with Brian on this chapter, after avoiding Learn.co for a few days, because this concept is so confusing.  I still don't understand how the concept of variables and functions being declared without values ... is taught by the challenge questions.  Instead, the challenges simply require (me) to move variables to other functions?  Ouch!  
I felt mugged at the end.  I'd tried to solve hoisting issues by declaring functions, declaring variables in and outside each function.  I tried to next sayMy inside sayMyName, to get Kristin to print.  

This is a really tough challenge to understand, partly due to the expectation that it had to do with hoisting.  (I am available by email, if I am not clearly explaining a noobie's perspective.)

**Comment by berniemelo** [comment]
Try to understand hoisting by steps.
 1. Any variable declared will be undefined at first at the very top (function expressions included.)
2. Then, any function will be put at the top (in the order they were written) but after Number 1.
3. Everything else will be executed line after line.
