### ISSUE TITLE
'Hoisting' test Times out after 2000ms

### ISSUE THREAD

**Issue by zombieknee** [learn-co-curriculum/js-hoisting-readme#15]
If you run the 'Hositing' lab in the Javascript track with no edits, the Learn IDE reports a failure, however in the web portal, the 'passes local tests' icon lights green indicating a pass. There is a fix:

replace

`  "scripts": {
    "test": "mocha -R mocha-multi --reporter-options nyan=-,json=.results.json"
  },`

with

`"scripts": {
      "test": "mocha --timeout 5000 -R mocha-multi --reporter-options nyan=-,json=.results.json"
  },`

in the package.json file.

Thanks to jd2rogers2 for the fix!

**Comment by Traci7822** [comment]
Issue still persists, fixed it with 
`"scripts": {
    "test": "mocha -R mocha-multi --reporter-options nyan=-,json=.results.json --timeout 5000"
  }`

**Comment by patrocc6** [comment]
Ran into this issue. The solution provided by @Traci7822 worked for me.
