### ISSUE TITLE
Not able to fork the Lab

### ISSUE THREAD

**Issue by anishshaw** [learn-co-curriculum/js-hoisting-readme#17]
Hi Team,
I accidently deleted 'js-hoisting' lab from my local i.e. learn IDE and now I am not able to re-fork that lab again or any other new labs.
Please help me with this issue.

**Comment by JessRudder** [comment]
Hi @anishshaw for issues like this, please use the "Ask a Question" feature in the right hand side of Learn.  A Learn Expert should be available to help you.
