### ISSUE TITLE
Test environment buggy

### ISSUE THREAD

**Issue by lucketta** [learn-co-curriculum/js-hoisting-readme#22]
I'm finding the test environment for LEARN IDE to be buggy. Sometimes when I start learn IDE it just opens up a large text editor and will not allow me to navigate anywhere. I have to close learn IDE and open it up again.

The second issue is with this hoisting test. I moved the function call "thisIsCrazy" and the "Kristen" name declaration to their correct spots and learn IDE threw an error saying timed out over 2000secs. I closed learn IDE and opened back up again and it was fine after that.

**Comment by JessRudder** [comment]
@lucketta please reach out to a Learn Expert using the "Ask a Question" feature in Learn in order to get help.
