### ISSUE TITLE
Test not working in IDE

### ISSUE THREAD

**Issue by CMahon92** [learn-co-curriculum/js-hoisting-readme#24]
1) hoisting "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)

**Comment by codeBueno** [comment]
This same error is still occurring in the hoisting lab when attempting to test code.

**Comment by maxwellbenton** [comment]
Hi @CMahon92,

Thank you for reporting this issue. We've updated this lab and corrected the package that was causing this problem. This issue should be resolved for students going forward.

Thank you for contributing!
