### ISSUE TITLE
Issue: Cannot complete the JavaScript hoisting lab due to a module error.

### ISSUE THREAD

**Issue by rarahman** [learn-co-curriculum/js-hoisting-readme#26]
Hi, this is Raiyan Rahman and I'm encountering the following issue when starting the JavaScript hoisting lab:

![image](https://user-images.githubusercontent.com/13613051/47679907-c36e4e00-db9b-11e8-8da8-f0a3b4fb5350.png)

It appears that the lab isn't loading properly due to missing library files. 

Please resolve this issue as it's preventing users from completing this lab.

Best Regards,

Raiyan Rahman

**Comment by codeBueno** [comment]
This issue still exists in the hoisting lab.
When running the test of the code, the following error appears:
Error: Cannot find module 'jsdon/lib/old-api'

**Comment by maxwellbenton** [comment]
Hi @rarahman, 

Thank you for reporting this issue. We've updated this lab and corrected the package that was causing this problem. This issue should be resolved for students going forward.

Thank you for contributing!
